server:
  port: 8082
  servlet:
    context-path: /sse-client
spring:
  application:
    name: sse-client
  ai:
    mcp:
      client:
        enabled: true
        name: sse-mcp-client
        version: 1.0.0
        request-timeout: 20s
        type: sync
        toolcallback:
          # 自动把MCP的Tool注册给Spring AI ChatClient，直接Agent调用
          enabled: true
        sse:
          connections:
            sse-server: # 自定义名称，可以配置多个MCP Server
              url: http://localhost:8081
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:3b-instruct
