<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zhoubyte</groupId>
        <artifactId>scorpio-java</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>scorpio-cloud-stream</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>scorpio-cloud-stream-rabbit</module>
        <module>scorpio-cloud-stream-kafka</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <stream.version>3.0.12.RELEASE</stream.version>
        <springboot.version>4.0.6</springboot.version>
    </properties>

</project>