server:
  port: 8080
  servlet:
    context-path: /stdio-server
spring:
  application:
    name: stdio-client
  ai:
    mcp:
      client:
        enabled: true
        name: stdio-mcp-client
        version: 1.0.0
        request-timeout: 20s
        type: sync
        toolcallback:
          # 自动把MCP的Tool注册给Spring AI ChatClient，直接Agent调用
          enabled: true
        stdio:
          connections:
            stdio-server: # 自定义名称，可以配置多个MCP Server
              command: java
              args:
#                - "-Dspring.ai.mcp.server.stdio=true"
#                - "-Dspring.main.web-application-type=none"
#                - "-Dlogging.pattern.console=" # 关闭server控制台输出，防止污染stdout
                - "-jar"
                - "/Users/zhoubyte/project/java/scorpio-java/scorpio-ai/spring-ai/mcp-server/stdio/target/stdio-0.0.1-SNAPSHOT.jar"
              env:
                DEBUG: true
#          servers-configuration: stdio-mcp-server.json
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:3b-instruct


